# Generated by Django 3.2.4 on 2021-07-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0012_alter_mascota_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('Run', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Numero de rut')),
                ('NombreCompleto', models.CharField(max_length=50, verbose_name='Nombre completo')),
                ('Pais', models.CharField(max_length=30, verbose_name='Pais')),
                ('Ciudad', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('Comuna', models.CharField(max_length=30, verbose_name='Comuna')),
                ('Direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('Telefono', models.IntegerField(verbose_name='Telefono')),
                ('Email', models.EmailField(max_length=30, verbose_name='Email')),
                ('Moneda', models.CharField(max_length=20, verbose_name='Moneda de pago')),
                ('imagen', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
