# Generated by Django 3.2.4 on 2021-07-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0013_provedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='provedor',
            name='contrasenia',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
