# Generated by Django 3.2.4 on 2021-07-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0014_provedor_contrasenia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provedor',
            new_name='Provedor1',
        ),
    ]
