# Generated by Django 3.2.4 on 2021-07-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0015_rename_provedor_provedor1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor1',
            name='Moneda',
            field=models.IntegerField(choices=[[0, 'CLP'], [1, 'DOLAR']]),
        ),
    ]
