# Generated by Django 3.2.4 on 2021-07-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0016_alter_provedor1_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor1',
            name='contrasenia',
            field=models.CharField(default='androidparty.png', max_length=15, null=True),
        ),
    ]
