# Generated by Django 3.2.4 on 2021-07-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0017_alter_provedor1_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor1',
            name='contrasenia',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='provedor1',
            name='imagen',
            field=models.ImageField(default='androidparty.png', null=True, upload_to='media'),
        ),
    ]
