# Generated by Django 3.2.4 on 2021-07-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshopapp', '0018_auto_20210707_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provedor1',
            name='imagen',
            field=models.ImageField(default='noimagen.png', null=True, upload_to='media'),
        ),
    ]
